mappings:
  GoogleShoppingFeedExtension: ilateral\SilverStripe\GoogleShoppingFeed\extensions\GoogleShoppingFeedExtension
  GoogleProductCategory: ilateral\SilverStripe\GoogleShoppingFeed\model\GoogleProductCategory
  GoogleShoppingFeed: ilateral\SilverStripe\GoogleShoppingFeed\GoogleShoppingFeed
  GoogleShoppingFeedController: ilateral\SilverStripe\GoogleShoppingFeed\controllers\GoogleShoppingFeedController
