mappings:
  GoogleShoppingFeedExtension: ilateral\SilverStripe\GoogleShoppingFeed\Extensions\Extension
  GoogleProductCategory: ilateral\SilverStripe\GoogleShoppingFeed\Model\GoogleProductCategory
  GoogleShoppingFeed: ilateral\SilverStripe\GoogleShoppingFeed\GoogleShoppingFeed
  GoogleShoppingFeedController: ilateral\SilverStripe\GoogleShoppingFeed\Control\GoogleShoppingFeedController
